insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Camiseta Hulk','Camiseta fondo Entero con estampado de Hulk',100,'/images/camiseta-hulk-marvel.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Camiseta Ironman','Camiseta Ironman, La tela de esta prenda es suave, Costura reforzada',50,'/images/camiseta-ironman-marvel.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Vaso Linterna verde DC','Vaso mediano de vidrio con logo de linterna verde ',100,'/images/Vaso linterna verde.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Vaso Superman DC','Vaso mediano de vidrio con logo de Superman ',100,'/images/vaso superman.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Vaso Flash DC','Vaso mediano de vidrio con logo de Flash ',100,'/images/vaso flash.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Vaso Batman DC','Vaso mediano de vidrio con logo de Batman',100,'/images/vaso Batman.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Vaso Marvel Stan Lee','vaso para bebidas calientes, Stan lee y el  guantelete del infinito',100,'/images/vaso stan lee.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Avengers, las gemas del infinito','Comic Marvel, Avenger las gemas del infinito.',100,'/images/Comics avengers las gemas del infinito.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Avengers, Thanos vs Hulk','Comic Marvel, Avengers Thanos vs Hulk',100,'/images/Avengers Thanos vs Hulk.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Avengers vs Thanos','Comic Marvel, Avengers vs Thanos',100,'/images/Avengers versus Thanos.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('DC Heroes in crisis','Comic DC Heroes in crisis',100,'/images/Comic Hroes in crisis.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Dc Injustice','Comic DC  deluxe injustice Gods among us',100,'/images/Comic injustice.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Spider man figura de acción','Spider de 26 cm, figura de acción Marvel',100,'/images/Juguete Spider man.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Guantelete del infinito','Marvel, guantelete del infinito.',100,'/images/Juguete guantelete del infinito.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Thanos figura de acción','Marvel, Thanos Endgame 29cm',100,'/images/Juguete Thanos.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Superman lanzadiscos','DC, Superman lanzadiscos y armadura intercambiable 26cm',100,'/images/Juguete Superman.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Batman lanzadiscos','DC, Batman lanzadiscos, 26 cm',100,'/images/juguetes Batman.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Vaso pitillo Hulk','Vaso Hulk Marvel con figurin y pitillo',100,'/images/Accesorio vaso pitillo hulk.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Vaso pitillo Spider man','Vaso Spider man con figurin y pitillo',100,'/images/Accesorio Vaso pitillo Spider man.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Vaso pitillo Capitan America','Vaso Capitan America, de vidrio. Con pitillo',100,'/images/Accesorio capitan america.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Dije superman DC','Dije texturizado Superman',100,'/images/Accesorio dije superman.png',CURRENT_DATE());
insert into productos(nombre,descripcion,cantidad,imagen,create_at) values('Gorra Batman DC','Gorra Batman DC de punto',100,'/images/Accesorio gorra batman.png',CURRENT_DATE());
